config/routes.rb
Rails.application.routes.draw do
  scope module: :public do
    root 'homes#top'
    get 'orders/complete' => 'orders#complete'
    post 'orders/new' => 'orders#new'
    resources :products, only: [:index, :show]
    resources :genres, only: [:show]
    resources :orders , except: [:destroy]
    resources :shipping_addresses, except: [:new]
    resources :cart_products, only: [:index, :update, :destroy, :create]
    resource :customers, only: [:edit, :update]
    post 'orders/confirm' => 'orders#confirm'
    get '/customers/my_page' => 'customers#show'
    get '/customers/check' => 'customers#check'
    patch '/customers/withdraw' => 'customers#withdraw'
    delete '/customers/cart_products/destroy_all' => 'cart_products#destroy_all'
    get 'homes/about' => 'homes#about'
  end
  namespace :admin do
    resources :products,  except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:show, :update, :index]
    resources :order_details, only: [:update]
    resources :homes, only: [:top]
    resources :customers, except: [:new, :create, :destroy]
  end

  Rails.application.routes.draw do
    devise_for :admin_users, controllers:{
      sessions: 'admin_users/sessions'
    }
    devise_for :customers, controllers:{
      registrations: 'customers/registrations',
      sessions: 'customers/sessions'
    }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :orders
         has_many :shipping_addresses
         has_many :products,through: :cart_product, source: :product, dependent: :destroy
         has_many :cart_products,dependent: :destroy
         

  def active_for_authentication?
    super && (is_deleted == false )
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(admin_customer_params)
    redirect_to admin_customer_path(customer)
  end

  private

  def admin_customer_params
    params.require(:customer).permit(:family_name, :first_name, :family_name_kana, :first_name_kana, :postal_code, :address, :phone, :email, :is_deleted)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name, :first_name, :family_name_kana, :first_name_kana, :postal_code, :address, :phone])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-1">
      <h4 class="customer-show">
        <%= @customer.family_name %><%= @customer.first_name %>
        さんの会員編集
      </h4>
    </div>
  </div>
  <div class="row">
    <div class="col-9 offset-1">
      <%= form_with model: @customer, url:admin_customer_path, local:true do |f| %>
        <table class="table table-borderless">
          <tbody>
            <tr>
              <td>会員ID</td>
              <td><%= @customer.id %></td>
            </tr>
            <tr>
              <td>氏名</td>
              <td><%= f.text_field :family_name %></td>
              <td><%= f.text_field :first_name %></td>
            </tr>
            <tr>
              <td>フリガナ</td>
              <td><%= f.text_field :family_name_kana %></td>
              <td><%= f.text_field :first_name_kana %></td>
            </tr>
            <tr>
              <td>郵便番号</td>
              <td><%= f.text_field :postal_code %></td>
            </tr>
            <tr>
              <td>住所</td>
              <td><%= f.text_field :address, size: 30 %></td>
            </tr>
            <tr>
              <td>電話番号</td>
              <td><%= f.text_field :phone %></td>
            </tr>
            <tr>
              <td>メールアドレス</td>
              <td><%= f.email_field :email %></td>
            </tr>
            <tr>
              <td>会員ステータス</td>
              <td>
                <%= f.radio_button :is_deleted , :false %>
                <%= f.label :is_deleted, "有効" %>
                <%= f.radio_button :is_deleted , :true %>
                <%= f.label :is_deleted, "退会" %>
              </td>
            </tr>
          </tbody>
        </table>
        <%= f.submit '変更を保存', class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-2">
      <h4 class="customer-index">会員一覧</h4>
    </div>
  </div>
  <div class="row">
    <div class="col-8 offset-2">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td>
              <%= link_to admin_customer_path(customer) do %>
                <%= customer.family_name %><%= customer.first_name %>
              <% end %>
            </td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_deleted == false %>
                <p class="text-success">有効</p>
              <% else %>
                <p class="text-secondary">退会</p>
              <% end %>
            </td>
           </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-2 offset-5">
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <h4 class="customer-show">
        <%= @customer.family_name %><%= @customer.first_name %>
        さんの会員情報
      </h4>
    </div>
  </div>
  <div class="row">
    <div class="col-6 offset-1">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td>氏名</td>
            <td><%= @customer.family_name %><%= @customer.first_name %></td>
          </tr>
          <tr>
            <td>フリガナ</td>
            <td><%= @customer.family_name_kana %><%= @customer.first_name_kana %></td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= @customer.phone %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @customer.email  %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td>
              <% if @customer.is_deleted == false %>
                <p class="text-success">有効</p>
              <% else %>
                <p class="text-secondary">退会</p>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-2 offset-3">
      <%= link_to '編集する', edit_admin_customer_path(@customer), class: 'btn btn-success' %>
    </div>
    <div class="col-3">
      <%= link_to '注文履歴一覧を見る', admin_orders_path(order_sort: 1,customer_id: @customer.id), class: 'btn btn-primary' %>
    </div>
  </div>
</div>