config/routes.rb
Rails.application.routes.draw do
  scope module: :public do
    root 'homes#top'
    get 'orders/complete' => 'orders#complete'
    post 'orders/new' => 'orders#new'
    resources :products, only: [:index, :show]
    resources :genres, only: [:show]
    resources :orders , except: [:destroy]
    resources :shipping_addresses, except: [:new]
    resources :cart_products, only: [:index, :update, :destroy, :create]
    resource :customers, only: [:edit, :update]
    post 'orders/confirm' => 'orders#confirm'
    get '/customers/my_page' => 'customers#show'
    get '/customers/check' => 'customers#check'
    patch '/customers/withdraw' => 'customers#withdraw'
    delete '/customers/cart_products/destroy_all' => 'cart_products#destroy_all'
    get 'homes/about' => 'homes#about'
  end
  namespace :admin do
    resources :products,  except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:show, :update, :index]
    resources :order_details, only: [:update]
    resources :homes, only: [:top]
    resources :customers, except: [:new, :create, :destroy]
  end

  Rails.application.routes.draw do
    devise_for :admin_users, controllers:{
      sessions: 'admin_users/sessions'
    }
    devise_for :customers, controllers:{
      registrations: 'customers/registrations',
      sessions: 'customers/sessions'
    }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
    belongs_to :customer
    belongs_to :product
    validates :cart_count, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :orders
         has_many :shipping_addresses
         has_many :products,through: :cart_product, source: :product, dependent: :destroy
         has_many :cart_products,dependent: :destroy
         

  def active_for_authentication?
    super && (is_deleted == false )
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :products
end

app/models/oeerder_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :product
    
    enum production_status: {製作不可:0, 製作待ち:1, 製作中:2, 製作完了:3}, _prefix: true
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer, optional: true
    has_many :order_details, dependent: :destroy
    accepts_nested_attributes_for :order_details


    validates_acceptance_of :confirming, allow_nil: false, on: :create
    after_validation :check_confirming

    def check_confirming
      errors.delete(:confirming)
      self.confirming = errors.empty? ? '1' : ''
    end

    validates :order_name, presence: true
    validates :order_address, presence: true
    validates :order_postal_code, presence: true
    validates :payment_method, presence: true

    enum order_status: {入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}, _prefix: true
    enum payment_method: {クレジットカード:1, 銀行振込:2}
    
    
    
      
    

    array = []
    CartProduct.all.each do |p|
    array << p.product.no_tax_price * 1.1
    end

    @total_price = array.sum
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :product
    
    
    
    enum production_status: {製作不可:0, 製作待ち:1, 製作中:2, 製作完了:3}, _prefix: true
    
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :cart_products,dependent: :destroy
    belongs_to :customer, optional: true

    has_many :order_details
    belongs_to :genre
    attachment :image
end

app/models/public.rb
module Public
  def self.table_name_prefix
    'public_'
  end
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
    belongs_to :customer
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 private

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(AdminUser)
        admin_orders_path
    else
        customers_my_page_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    return new_admin_user_session_path if resource_or_scope == :admin_user
    root_path
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shipping_addresses_helper.rb
module ShippingAddressesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-4 offset-1">
      <h4 class="genre-index">ジャンル編集</h4>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <%= form_with model:@genre, url:"/admin/genres/#{@genre.id}", local: true do |f| %>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>ジャンル名</td>
            <td><%= f.text_field :name, class: "form-control" %></td>
            <td><%= f.submit "変更を保存", class: "btn btn-success" %></td>
          </tr>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-4 offset-1">
      <h4 class="genre-index">ジャンル一覧・追加</h4>
    </div>
  </div>
  <div class="row">
    <div class="col-5">
      <%= form_with model:@genre, url:"/admin/genres", local: true do |f| %>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>ジャンル名</td>
            <td><%= f.text_field :name, class: "form-control" %></td>
            <td><%= f.submit "新規登録", class: "btn btn-success" %></td>
          </tr>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-4">
      <table class="table">
        <thead class="thead-light">
          <th>ジャンル</th>
          <th></th>
        </thead>
        <% @genres.each do |genre| %>
        <tbody>
          <tr>
            <td><%= genre.name %></td>
            <td><%= link_to "編集する",edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>