config/routes.rb
Rails.application.routes.draw do
  scope module: :public do
    root 'homes#top'
    get 'orders/complete' => 'orders#complete'
    post 'orders/new' => 'orders#new'
    resources :products, only: [:index, :show]
    resources :genres, only: [:show]
    resources :orders , except: [:destroy]
    resources :shipping_addresses, except: [:new]
    resources :cart_products, only: [:index, :update, :destroy, :create]
    resource :customers, only: [:edit, :update]
    post 'orders/confirm' => 'orders#confirm'
    get '/customers/my_page' => 'customers#show'
    get '/customers/check' => 'customers#check'
    patch '/customers/withdraw' => 'customers#withdraw'
    delete '/customers/cart_products/destroy_all' => 'cart_products#destroy_all'
    get 'homes/about' => 'homes#about'
  end
  namespace :admin do
    resources :products,  except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:show, :update, :index]
    resources :order_details, only: [:update]
    resources :homes, only: [:top]
    resources :customers, except: [:new, :create, :destroy]
  end

  Rails.application.routes.draw do
    devise_for :admin_users, controllers:{
      sessions: 'admin_users/sessions'
    }
    devise_for :customers, controllers:{
      registrations: 'customers/registrations',
      sessions: 'customers/sessions'
    }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
    belongs_to :customer
    belongs_to :product
    validates :cart_count, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :orders
         has_many :shipping_addresses
         has_many :products,through: :cart_product, source: :product, dependent: :destroy
         has_many :cart_products,dependent: :destroy
         

  def active_for_authentication?
    super && (is_deleted == false )
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :products
end

app/models/oeerder_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :product
    
    enum production_status: {製作不可:0, 製作待ち:1, 製作中:2, 製作完了:3}, _prefix: true
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer, optional: true
    has_many :order_details, dependent: :destroy
    accepts_nested_attributes_for :order_details


    validates_acceptance_of :confirming, allow_nil: false, on: :create
    after_validation :check_confirming

    def check_confirming
      errors.delete(:confirming)
      self.confirming = errors.empty? ? '1' : ''
    end

    validates :order_name, presence: true
    validates :order_address, presence: true
    validates :order_postal_code, presence: true
    validates :payment_method, presence: true

    enum order_status: {入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}, _prefix: true
    enum payment_method: {クレジットカード:1, 銀行振込:2}
    
    
    
      
    

    array = []
    CartProduct.all.each do |p|
    array << p.product.no_tax_price * 1.1
    end

    @total_price = array.sum
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :product
    
    
    
    enum production_status: {製作不可:0, 製作待ち:1, 製作中:2, 製作完了:3}, _prefix: true
    
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :cart_products,dependent: :destroy
    belongs_to :customer, optional: true

    has_many :order_details
    belongs_to :genre
    attachment :image
end

app/models/public.rb
module Public
  def self.table_name_prefix
    'public_'
  end
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
    belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 private

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(AdminUser)
        admin_orders_path
    else
        customers_my_page_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    return new_admin_user_session_path if resource_or_scope == :admin_user
    root_path
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shipping_addresses_helper.rb
module ShippingAddressesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/721f0cdc29.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <body class="d-flex flex-column vh-100">
     <header class="shadow-sm">
      <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
       <div class="container">
        <a class="navbar-brand p-3" href="/"><%="ながのCAKE" %></a>
         <!--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">-->
         <!-- <span class="navbar-toggler-icon"></span>-->
         <!--</button>-->
         <!--<div class="collapse navbar-collapse" id="navbarNavDropdown">-->
        　<ul class="list-group list-group-horizontal">
           <% if customer_signed_in? %>
           <li class = "nav-item mr-3">
             <p>ようこそ、<%= current_customer.family_name %>さん！</p>
           </li>
           <li class = "nav-item mr-3">
             <%= link_to "マイページ", customers_my_page_path, class: "btn btn-outline-secondary" %>
           </li>
           <li class = "nav-item mr-3">
            <%= link_to "商品一覧", products_path, class: "btn btn-outline-secondary" %>
           </li>
           <li class = "nav-item mr-3">
            <%= link_to "カート", cart_products_path, class: "btn btn-outline-secondary" %>
          </li>
          <li class = "nav-item mr-3">
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-secondary" %>
          </li>
          <% elsif admin_user_signed_in? %>
          <li class = "nav-item mr-3">
            <%= link_to "商品一覧", admin_products_path, class: "btn btn-outline-secondary" %>
          </li>
          <li class = "nav-item mr-3">
            <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-secondary" %>
          </li>
          <li class = "nav-item mr-3">
           <%= link_to "注文履歴一覧", admin_orders_path(order_sort: 0), class: "btn btn-outline-secondary" %>
          </li>
          <li class = "nav-item mr-3">
            <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-secondary" %>
          </li>
          <li class = "nav-item mr-3">
            <%= link_to "ログアウト", destroy_admin_user_session_path, method: :delete, class: "btn btn-outline-secondary" %>
          </li>
          <% else %>
          <li class = "nav-item mr-3">
            <%= link_to "About", homes_about_path, class: "btn btn-outline-secondary" %>
          </li>
          <li class = "nav-item mr-3">
            <%= link_to "商品一覧", products_path, class: "btn btn-outline-secondary" %>
          </li>
          <li class = "nav-item mr-3">
            <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-secondary" %>
          </li>
          <li class = "nav-item mr-3">
            <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-secondary" %>
          </li>
          <% end %>
         </ul>
        </div>
    　 </nav>
    </header>
    <main class ="mb-auto">
      <%= yield %>
    </main>
    <footer>
      <div class="footer"></div>
    </footer>
  </body>
</html>